/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kxw.graalvm;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    //curl "http://127.0.0.1:8080"
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
